import Link from 'next/link'
import { requireAdmin, adminDataClient, formatDate, statusClass } from '@/lib/admin'

export default async function ShopsPage({ searchParams }: { searchParams: Promise<{ q?: string; status?: string }> }) {
  const { supabase } = await requireAdmin(); const params = await searchParams; const q = params.q?.trim() ?? ''; const status = params.status ?? 'all'
  const { data: shops } = await supabase.from('shop_settings').select('shop_id,name,address,phone,created_at,subscription_status').order('created_at', { ascending: false })
  const rows = shops ?? []; const ids = rows.map((row) => row.shop_id); const { data: subs } = ids.length ? await supabase.from('subscriptions').select('shop_id,plan,status,current_period_end').in('shop_id', ids) : { data: [] }; const subMap = new Map((subs ?? []).map((row) => [row.shop_id, row])); const roleRows = ids.length ? (await supabase.from('user_roles').select('shop_id,user_id,full_name').in('shop_id', ids)).data ?? [] : []; const userIds = roleRows.map((row) => row.user_id); const { data: users } = userIds.length ? await adminDataClient().auth.admin.listUsers({ perPage: 1000 }) : { data: { users: [] } }; const emailMap = new Map((users?.users ?? []).map((user) => [user.id, user.email]))
  const filtered = rows.filter((shop) => { const sub = subMap.get(shop.shop_id); const owner = roleRows.find((row) => row.shop_id === shop.shop_id); const haystack = `${shop.name ?? ''} ${emailMap.get(owner?.user_id ?? '') ?? ''}`.toLowerCase(); return (!q || haystack.includes(q.toLowerCase())) && (status === 'all' || (sub?.status ?? shop.subscription_status) === status) })
  return <section className="p-5 sm:p-8"><h1 className="text-3xl font-bold">Shops</h1><p className="mt-2 text-stone-500">Every business on ShopOS.</p><form className="mt-6 flex flex-col gap-3 sm:flex-row"><input name="q" defaultValue={q} placeholder="Search shop or owner email" className="h-11 flex-1 rounded-xl border border-stone-200 bg-white px-4 text-sm outline-none focus:border-emerald-500" /><button className="rounded-xl bg-emerald-600 px-5 font-semibold text-white">Search</button></form><div className="my-5 flex gap-2 overflow-x-auto">{['all','trialing','active','expired'].map((item) => <Link key={item} href={`/admin/shops?status=${item}${q ? `&q=${encodeURIComponent(q)}` : ''}`} className={`rounded-full px-4 py-2 text-sm font-semibold capitalize ${status === item ? 'bg-emerald-600 text-white' : 'bg-white text-stone-600 ring-1 ring-stone-200'}`}>{item}</Link>)}</div><div className="overflow-x-auto rounded-2xl border border-stone-200 bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-stone-50 text-xs uppercase tracking-wide text-stone-500"><tr>{['Shop name','Owner email','Phone','Status','Plan','Period ends','Actions'].map((head) => <th key={head} className="px-5 py-3">{head}</th>)}</tr></thead><tbody>{filtered.map((shop) => { const sub = subMap.get(shop.shop_id); const owner = roleRows.find((row) => row.shop_id === shop.shop_id); return <tr key={shop.shop_id} className="border-t border-stone-100 hover:bg-stone-50"><td className="px-5 py-4 font-semibold"><Link href={`/admin/shops/${shop.shop_id}`}>{shop.name ?? 'Unnamed shop'}</Link></td><td className="px-5 py-4 text-stone-600">{emailMap.get(owner?.user_id ?? '') ?? '—'}</td><td className="px-5 py-4 text-stone-600">{shop.phone ?? '—'}</td><td className="px-5 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusClass(sub?.status ?? shop.subscription_status)}`}>{sub?.status ?? shop.subscription_status ?? 'unknown'}</span></td><td className="px-5 py-4 capitalize text-stone-600">{sub?.plan ?? '—'}</td><td className="px-5 py-4 text-stone-600">{formatDate(sub?.current_period_end)}</td><td className="px-5 py-4"><Link href={`/admin/shops/${shop.shop_id}`} className="font-semibold text-emerald-700">View</Link></td></tr> })}</tbody></table></div></section>
}
