'use client'

import { useAuth, AuthProvider } from '@/components/auth/auth-provider'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'

function daysLeft(date?: string) { return Math.max(0, Math.ceil((new Date(date ?? Date.now()).getTime() - Date.now()) / 86400000)) }
export default function BillingPage() { return <AuthProvider><BillingAccess /></AuthProvider> }
function BillingAccess() { const { role, loading } = useAuth(); if (loading) return null; if (role?.role !== 'owner') return <main className="p-10 text-center text-stone-600">Billing is available to shop owners only.</main>; return <BillingContent /> }
function BillingContent() { const { shop } = useAuth(); const days = daysLeft(shop?.subscription_ends_at); const status = shop?.subscription_status ?? 'trialing'; const end = shop?.subscription_ends_at ? new Date(shop.subscription_ends_at).toLocaleDateString('en-PK',{dateStyle:'medium'}) : 'soon'; return <main className="min-h-screen bg-[#fbfaf7] p-6 text-stone-900 sm:p-10"><div className="mx-auto max-w-5xl"><h1 className="text-3xl font-bold">Keep your shop moving</h1><p className="mt-2 text-stone-500">Simple plans and friendly support for your business.</p><div className="mt-8 grid gap-6 lg:grid-cols-3"><Card><CardHeader><CardTitle>Status</CardTitle></CardHeader><CardContent><Badge className={status === 'active' ? 'bg-emerald-600' : status === 'expired' ? 'bg-rose-600' : 'bg-amber-500'}>{status === 'trialing' ? `Free Trial — ${days} days left` : status === 'active' ? `Active — renews ${end}` : 'Expired — renew now'}</Badge></CardContent></Card><Card><CardHeader><CardTitle>Basic plan</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">₨1,500<span className="text-sm font-normal text-stone-500">/month</span></p><ul className="mt-4 space-y-2 text-sm text-stone-600">{['Sell at the counter','Track stock','Customer khata','Basic reports','Offline mode'].map((item) => <li key={item}>✓ {item}</li>)}</ul></CardContent></Card><Card><CardHeader><CardTitle>Payment options</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div><p className="font-semibold">Meezan Bank</p><p>ShopOS Technologies</p><p>Account: 0123-4567890123</p><p>IBAN: PK00MEZN0001234567890123</p></div><div><p className="font-semibold">JazzCash / EasyPaisa</p><p>03044463268 · ShopOS</p></div><a href="https://wa.me/923044463268" target="_blank" rel="noreferrer"><Button className="w-full bg-emerald-600 hover:bg-emerald-700">Send payment screenshot on WhatsApp</Button></a><p className="text-xs text-stone-500">We&apos;ll activate your account within 24 hours of receiving payment.</p></CardContent></Card></div></div></main> }
