'use client'

import { useState } from 'react'
import { Mail, Lock, User, Store, ArrowLeft } from 'lucide-react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'

function Shell({ children, title, description }: { children: React.ReactNode; title: string; description: string }) { return <main className="flex min-h-screen items-center justify-center bg-[#fbfaf7] px-4 py-10"><div className="w-full max-w-[420px]"><div className="mb-8 text-center"><div className="mx-auto mb-4 flex size-12 items-center justify-center rounded-2xl bg-emerald-600 text-white shadow-lg shadow-emerald-600/20"><Store /></div><div className="text-2xl font-bold tracking-tight text-stone-900">Shop<span className="text-emerald-600">OS</span></div><p className="mt-1 text-sm text-stone-500">Run your shop, the easy way</p></div><section className="rounded-3xl border border-stone-200/80 bg-white p-7 shadow-xl shadow-stone-900/5"><h1 className="text-2xl font-bold text-stone-900">{title}</h1><p className="mt-2 text-sm text-stone-500">{description}</p><div className="mt-6">{children}</div></section></div></main> }
function Field({ icon: Icon, ...props }: any) { return <div className="relative"><Icon className="absolute left-3 top-3 size-4 text-stone-400" /><input {...props} className="h-12 w-full rounded-xl border border-stone-200 bg-stone-50/60 pl-10 pr-3 text-sm outline-none transition focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/10" /></div> }
function ErrorText({ message }: { message: string }) { return message ? <p className="rounded-xl bg-red-50 px-3 py-2 text-sm text-red-700">{message}</p> : null }

export function LoginPage() { const router = useRouter(); const params = useSearchParams(); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const notice=params.get('message')==='updated'?'Password updated! You can now sign in.':''; const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');const supabase=createClient();const normalizedEmail=email.trim().toLowerCase();const {data:lock}=await supabase.rpc('is_login_locked',{p_email:normalizedEmail});if(lock?.locked){setError(`Account locked. Try again in ${Math.ceil(Number(lock.remaining_seconds)/60)} minute(s).`);setLoading(false);return}const {error:signInError}=await supabase.auth.signInWithPassword({email,password});if(signInError){const {data:failure}=await supabase.rpc('record_login_failure',{p_email:normalizedEmail});if(failure?.locked)setError('Too many attempts. Account locked for 3 hours.');else setError(`Wrong email or password. ${Math.max(0,3-Number(failure?.failed_count ?? 0))} attempt(s) left.`)}else{await supabase.rpc('record_login_success',{p_email:normalizedEmail});router.push(params.get('next')||'/dashboard')}setLoading(false)}; return <Shell title="Welcome back" description="Sign in to keep your shop moving."><form onSubmit={submit} className="flex flex-col gap-4"><Field icon={Mail} type="email" placeholder="Email address" value={email} onChange={(e:any)=>setEmail(e.target.value)} required /><Field icon={Lock} type="password" placeholder="Password" value={password} onChange={(e:any)=>setPassword(e.target.value)} required /><div className="flex items-center justify-between text-sm"><label className="flex items-center gap-2 text-stone-600"><input type="checkbox" className="size-4 accent-emerald-600" />Remember me</label><Link href="/forgot-password" className="font-medium text-emerald-700">Forgot password?</Link></div>{notice && <p className="rounded-xl bg-emerald-50 px-3 py-2 text-sm text-emerald-700">{notice}</p>}<ErrorText message={error}/><a href="https://wa.me/923044463268" target="_blank" rel="noreferrer" className="text-center text-xs font-medium text-emerald-700">Locked out? WhatsApp us</a><button disabled={loading} className="h-12 rounded-full bg-emerald-600 font-semibold text-white shadow-lg shadow-emerald-600/20 transition hover:bg-emerald-700 disabled:opacity-60">{loading?'Signing in…':'Sign in'}</button><p className="text-center text-sm text-stone-500">New here? <Link href="/signup" className="font-semibold text-emerald-700">Create an account</Link></p></form></Shell> }

export function SignupPage() { const router=useRouter(); const [form,setForm]=useState({fullName:'',shopName:'',email:'',password:'',confirm:''}); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const strength=form.password.length<6?'Weak':form.password.length<10?'Okay':'Strong'; const submit=async(e:React.FormEvent)=>{e.preventDefault();if(form.password!==form.confirm)return setError('Passwords do not match');setLoading(true);setError('');const supabase=createClient();const {data,error}=await supabase.auth.signUp({email:form.email,password:form.password,options:{data:{full_name:form.fullName,shop_name:form.shopName},emailRedirectTo:`${window.location.origin}/auth/callback`}});if(error)setError(error.message.includes('password')?'Choose a stronger password':'We could not create your account — please try again');else if(data.user&&data.session){const shopId=crypto.randomUUID();await supabase.from('user_roles').insert({user_id:data.user.id,shop_id:shopId,role:'owner',full_name:form.fullName});await supabase.from('shop_settings').insert({shop_id:shopId,name:form.shopName});router.push('/setup')}else router.push('/login?message=confirm');setLoading(false)};return <Shell title="Create your shop" description="Let’s get your shop set up!"><form onSubmit={submit} className="flex flex-col gap-3"><Field icon={User} placeholder="Full name" value={form.fullName} onChange={(e:any)=>setForm({...form,fullName:e.target.value})} required/><Field icon={Store} placeholder="Shop name" value={form.shopName} onChange={(e:any)=>setForm({...form,shopName:e.target.value})} required/><Field icon={Mail} type="email" placeholder="Email address" value={form.email} onChange={(e:any)=>setForm({...form,email:e.target.value})} required/><Field icon={Lock} type="password" placeholder="Password" value={form.password} onChange={(e:any)=>setForm({...form,password:e.target.value})} required/><div className="flex items-center justify-between px-1 text-xs text-stone-500"><span>Password strength</span><span className={strength==='Strong'?'text-emerald-600':strength==='Okay'?'text-amber-600':'text-red-600'}>{strength}</span></div><Field icon={Lock} type="password" placeholder="Confirm password" value={form.confirm} onChange={(e:any)=>setForm({...form,confirm:e.target.value})} required/><label className="flex items-start gap-2 py-2 text-xs text-stone-500"><input type="checkbox" required className="mt-0.5 size-4 accent-emerald-600"/>I agree to the terms and privacy policy.</label><ErrorText message={error}/><button disabled={loading} className="h-12 rounded-full bg-emerald-600 font-semibold text-white shadow-lg shadow-emerald-600/20 hover:bg-emerald-700 disabled:opacity-60">{loading?'Creating your shop…':'Create my shop'}</button><p className="text-center text-sm text-stone-500">Already have an account? <Link href="/login" className="font-semibold text-emerald-700">Sign in</Link></p></form></Shell> }

export function ForgotPasswordPage() { const [email,setEmail]=useState('');const [sent,setSent]=useState(false);const [loading,setLoading]=useState(false);const submit=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);await createClient().auth.resetPasswordForEmail(email,{redirectTo:`${window.location.origin}/auth/callback?next=/reset-password`});setSent(true);setLoading(false)};return <Shell title="Reset your password" description="We’ll help you get back in safely.">{sent?<div className="flex flex-col gap-4 text-center"><div className="mx-auto flex size-12 items-center justify-center rounded-full bg-emerald-50 text-emerald-600"><Mail/></div><p className="text-sm text-stone-600">Check your inbox — we sent a reset link to <strong>{email}</strong>.</p><Link href="/login" className="font-semibold text-emerald-700">Back to sign in</Link></div>:<form onSubmit={submit} className="flex flex-col gap-4"><Field icon={Mail} type="email" placeholder="Email address" value={email} onChange={(e:any)=>setEmail(e.target.value)} required/><button disabled={loading} className="h-12 rounded-full bg-emerald-600 font-semibold text-white hover:bg-emerald-700">{loading?'Sending…':'Send reset link'}</button><Link href="/login" className="flex items-center justify-center gap-2 text-sm font-medium text-stone-500"><ArrowLeft className="size-4"/>Back to sign in</Link></form>}</Shell> }

export function ResetPasswordPage() { const router=useRouter();const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [error,setError]=useState('');const submit=async(e:React.FormEvent)=>{e.preventDefault();if(password!==confirm)return setError('Passwords do not match');const {error}=await createClient().auth.updateUser({password});if(error)setError('Choose a stronger password');else { router.push('/login?message=updated'); }};return <Shell title="Choose a new password" description="Make it something only you know."><form onSubmit={submit} className="flex flex-col gap-4"><Field icon={Lock} type="password" placeholder="New password" value={password} onChange={(e:any)=>setPassword(e.target.value)} required/><Field icon={Lock} type="password" placeholder="Confirm new password" value={confirm} onChange={(e:any)=>setConfirm(e.target.value)} required/><ErrorText message={error}/><button className="h-12 rounded-full bg-emerald-600 font-semibold text-white hover:bg-emerald-700">Update password</button></form></Shell> }
