import { getDB, type Customer, type PendingCreditMove, type PendingSale, type PendingSaleInput, type PendingStockMove, type Product, type ShopSettings, type Supplier, type SyncLogEntry } from './db'

const safe = async <T>(fallback: T, fn: () => Promise<T>) => { try { return await fn() } catch { return fallback } }
export async function cacheProducts(products: Product[]) { await safe(undefined, async () => { const db = await getDB(); const tx = db.transaction('products_cache', 'readwrite'); await Promise.all(products.map((p) => tx.store.put(p))); await tx.done }) }
export async function getCachedProducts(filters: { search?: string; category?: string } = {}) { return safe<Product[]>([], async () => { const all = await (await getDB()).getAll('products_cache'); const q = filters.search?.toLowerCase(); return all.filter((p) => (!q || [p.name, p.barcode, p.sku].some((v) => v?.toLowerCase().includes(q))) && (!filters.category || p.category === filters.category)) }) }
export async function getCachedProductByBarcode(barcode: string) { return safe<Product | null>(null, async () => { const value = await (await getDB()).getFromIndex('products_cache', 'barcode', barcode); return value ?? null }) }
export async function cacheCustomers(customers: Customer[]) { await safe(undefined, async () => { const db = await getDB(); const tx = db.transaction('customers_cache', 'readwrite'); await Promise.all(customers.map((c) => tx.store.put(c))); await tx.done }) }
export async function getCachedCustomers({ search }: { search?: string } = {}) { return safe<Customer[]>([], async () => { const all = await (await getDB()).getAll('customers_cache'); const q = search?.toLowerCase(); return all.filter((c) => !q || [c.name, c.phone].some((v) => v?.toLowerCase().includes(q))) }) }
export async function cacheSuppliers(suppliers: Supplier[]) { await safe(undefined, async () => { const db = await getDB(); const tx = db.transaction('suppliers_cache', 'readwrite'); await Promise.all(suppliers.map((s) => tx.store.put(s))); await tx.done }) }
export async function getCachedSuppliers() { return safe<Supplier[]>([], () => getDB().then((db) => db.getAll('suppliers_cache'))) }
export async function cacheSettings(settings: ShopSettings) { await safe(undefined, () => getDB().then((db) => db.put('settings_cache', settings))) }
export async function getCachedSettings(shop_id: string) { return safe<ShopSettings | null>(null, async () => { const value = await (await getDB()).get('settings_cache', shop_id); return value ?? null }) }
export async function queueSale(sale: PendingSaleInput) { const local_id = crypto.randomUUID(); await safe(undefined, () => getDB().then((db) => db.put('pending_sales', { ...sale, local_id, status: 'pending', attempts: 0, created_at: Date.now() }))); return local_id }
export async function queueStockMove(product_id: string, delta: number, reason: string) { const local_id = crypto.randomUUID(); await safe(undefined, () => getDB().then((db) => db.put('pending_stock_moves', { local_id, product_id, delta, reason, status: 'pending', attempts: 0, created_at: Date.now() }))); return local_id }
export async function queueCreditMove(customer_id: string, amount: number, type: string, note?: string) { const local_id = crypto.randomUUID(); await safe(undefined, () => getDB().then((db) => db.put('pending_credit_moves', { local_id, customer_id, amount, type, note, status: 'pending', attempts: 0, created_at: Date.now() }))); return local_id }
export async function getPendingSales() { return safe<PendingSale[]>([], () => getDB().then((db) => db.getAllFromIndex('pending_sales', 'status', 'pending'))) }
export async function getPendingStockMoves() { return safe<PendingStockMove[]>([], () => getDB().then((db) => db.getAllFromIndex('pending_stock_moves', 'status', 'pending'))) }
export async function getPendingCreditMoves() { return safe<PendingCreditMove[]>([], () => getDB().then((db) => db.getAllFromIndex('pending_credit_moves', 'status', 'pending'))) }
type QueueStore = 'pending_sales' | 'pending_stock_moves' | 'pending_credit_moves'
export async function markSynced(store: QueueStore, local_id: string) { await safe(undefined, async () => { const db = await getDB(); const row = await db.get(store, local_id); if (row) await db.put(store, { ...row, status: 'synced' }) }) }
export async function markFailed(store: QueueStore, local_id: string, error: string) { await safe(undefined, async () => { const db = await getDB(); const row = await db.get(store, local_id); if (row) await db.put(store, { ...row, status: 'failed', error }) }) }
export async function incrementAttempts(store: QueueStore, local_id: string) { await safe(undefined, async () => { const db = await getDB(); const row = await db.get(store, local_id); if (row) await db.put(store, { ...row, attempts: row.attempts + 1 }) }) }
export async function clearSyncedOlderThan(days: number) { await safe(undefined, async () => { const db = await getDB(); const cutoff = Date.now() - days * 86400000; for (const store of ['pending_sales', 'pending_stock_moves', 'pending_credit_moves'] as QueueStore[]) { const rows = await db.getAll(store); await Promise.all(rows.filter((r) => r.status === 'synced' && r.created_at < cutoff).map((r) => db.delete(store, r.local_id))) } }) }
export async function logSync(entry: Omit<SyncLogEntry, 'id' | 'created_at'>) { await safe(undefined, () => getDB().then((db) => db.add('sync_log', { ...entry, created_at: Date.now() }))) }
export async function getRecentSyncLog(limit = 100) { return safe<SyncLogEntry[]>([], async () => { const rows = await (await getDB()).getAllFromIndex('sync_log', 'created_at'); return rows.reverse().slice(0, limit) }) }
export async function setMeta(key: string, value: unknown) { await safe(undefined, () => getDB().then((db) => db.put('meta', { key, value }))) }
export async function getMeta<T>(key: string) { return safe<T | null>(null, async () => { const row = await (await getDB()).get('meta', key); return row ? row.value as T : null }) }
